### ISSUE TITLE
Broken phone images seems to assess only the damage value of outer parts of the phone..

### ISSUE THREAD

**Issue by shalabh2101** [SJSUFall2019-CMPE272/brokenPhone#1]
The model seems to predict the damage value of the outer parts like Screen, Camera or body of the phone.  Will there be a way to assess the internal working of the phone like processing speed, battery life, motherboard damage etc?  
If the model is only estimating the damage value based on images, then it is vulnerable to the incorrect valuation as an old phone can resemble a new device by just changing the outer parts.
Will there be any Human Intervention required to assess the overall damage? If yes then how it will help to improve the current process.

**Comment by duvvurisrihari** [comment]
As a  prototype model we are currently examining the outer damage of the phone and not dwelling into the diagnosis of the elements which would require another software counterpart that probes into the internal components' performance.This idea of internal analysis could be implemented in a subsequent upgrade to the existing application and taken in as a scale up to the current version.
