### ISSUE TITLE
Price Estimation may give unexpected result  for a new phone Model for which there is no training data.

### ISSUE THREAD

**Issue by shalabh2101** [SJSUFall2019-CMPE272/brokenPhone#2]
Price prediction seems to be dependent on the type of mobile company as each company may have different sizes and material specifications. Let's say a new company has launched a new series of mobile phones, the machine learning model will predict the price based on the training data of old companies' images. This might led to an unexpected result. It is like predicting the "OnePlus" price from the model trained on the datasets of "Samsung", "Nokia", or "iPhone".
Is there a way to handle the varieties of mobile phones without needing to ensure that the training data must contain all types of mobile phones? or Will it be necessary to have the training data that contains all types of mobile phones?

**Comment by duvvurisrihari** [comment]
The prediction model functions partly on the model and company name provided by the user, used to retrieve the price of the mobile from the database. Moreover, the prediction is not entirely dependent upon the model and only uses the details to gauge the market price of the phone. Initially, the database would include a limited set of companies and phone models and can, later on, be updated to support a wide variety of them. To work with the user having an unsupported piece, feedback will be obtained requesting for the company and model of the device. This feedback to include a newer model would be taken into consideration in the update cycle of the application
